### ISSUE TITLE
Provider com.linkedin.spark.datasources.tfrecord.DefaultSource could not be instantiated

### ISSUE THREAD

**Issue by Mowar** [linkedin/spark-tfrecord#17]
I try to use example.

```java
import org.apache.commons.io.FileUtils
import org.apache.spark.SparkConf
import org.apache.spark.sql.{DataFrame, Row, SparkSession}
import org.apache.spark.sql.catalyst.expressions.GenericRow
import org.apache.spark.sql.types._
/**
 * descriptions:
 *
 * author: shuzeyuan
 * date: 2020 - 12 - 05 10:49 下午
 */
object TestTFExample {

  def main(args: Array[String]): Unit = {

    val path = "test-output.tfrecord"
    val testRows: Array[Row] = Array(
      new GenericRow(Array[Any](11, 1, 23L, 10.0F, 14.0, List(1.0, 2.0), "r1")),
      new GenericRow(Array[Any](21, 2, 24L, 12.0F, 15.0, List(2.0, 2.0), "r2")))
    val schema = StructType(List(StructField("id", IntegerType),
      StructField("IntegerCol", IntegerType),
      StructField("LongCol", LongType),
      StructField("FloatCol", FloatType),
      StructField("DoubleCol", DoubleType),
      StructField("VectorCol", ArrayType(DoubleType, true)),
      StructField("StringCol", StringType)))
    val resolutionPath = this.getClass.getResource("/jar/spark-tfrecord_2.12-0.2.3.jar")
    val conf = new SparkConf()
      .setMaster("local")
      .setAppName("featureEngingForHotItem")
      .set("spark.submit.deployMode", "client")
      .setJars(Seq(resolutionPath.getPath))

//      .config("spark.jars", "location/to/spark-tensorflow-connector_2.11-1.12.0.jar"
    val spark = SparkSession.builder.config(conf).getOrCreate()
    val rdd = spark.sparkContext.parallelize(testRows)

    //Save DataFrame as TFRecords
    val df: DataFrame = spark.createDataFrame(rdd, schema)
    df.write.format("tfrecord").option("recordType", "Example").save(path)

    //Read TFRecords into DataFrame.
    //The DataFrame schema is inferred from the TFRecords if no custom schema is provided.
    val importedDf1: DataFrame = spark.read.format("tfrecord").option("recordType", "Example").load(path)
    importedDf1.show()

    //Read TFRecords into DataFrame using custom schema
    val importedDf2: DataFrame = spark.read.format("tfrecord").schema(schema).load(path)
    importedDf2.show()
  }

}
```

but I get some error.

20/12/06 00:33:40 WARN Utils: Your hostname, Mowar-2.local resolves to a loopback address: 127.0.0.1; using 172.20.10.2 instead (on interface en0)
20/12/06 00:33:40 WARN Utils: Set SPARK_LOCAL_IP if you need to bind to another address
20/12/06 00:33:40 INFO SparkContext: Running Spark version 2.4.3
20/12/06 00:33:40 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
20/12/06 00:33:41 INFO SparkContext: Submitted application: featureEngingForHotItem
20/12/06 00:33:41 INFO SecurityManager: Changing view acls to: shuzeyuan
20/12/06 00:33:41 INFO SecurityManager: Changing modify acls to: shuzeyuan
20/12/06 00:33:41 INFO SecurityManager: Changing view acls groups to: 
20/12/06 00:33:41 INFO SecurityManager: Changing modify acls groups to: 
20/12/06 00:33:41 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users  with view permissions: Set(shuzeyuan); groups with view permissions: Set(); users  with modify permissions: Set(shuzeyuan); groups with modify permissions: Set()
20/12/06 00:33:42 INFO Utils: Successfully started service 'sparkDriver' on port 49300.
20/12/06 00:33:42 INFO SparkEnv: Registering MapOutputTracker
20/12/06 00:33:42 INFO SparkEnv: Registering BlockManagerMaster
20/12/06 00:33:42 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
20/12/06 00:33:42 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
20/12/06 00:33:42 INFO DiskBlockManager: Created local directory at /private/var/folders/9z/ct0p8j1d74z5yp89434ncgbc0000gn/T/blockmgr-6174b4de-60ea-4d42-bcb3-634ece99b839
20/12/06 00:33:42 INFO MemoryStore: MemoryStore started with capacity 2004.6 MB
20/12/06 00:33:42 INFO SparkEnv: Registering OutputCommitCoordinator
20/12/06 00:33:42 INFO Utils: Successfully started service 'SparkUI' on port 4040.
20/12/06 00:33:42 INFO SparkUI: Bound SparkUI to 0.0.0.0, and started at http://172.20.10.2:4040
20/12/06 00:33:42 INFO SparkContext: Added JAR /Users/shuzeyuan/IdeaProjects/SparrowRecSys/target/classes/jar/spark-tfrecord_2.12-0.2.3.jar at spark://172.20.10.2:49300/jars/spark-tfrecord_2.12-0.2.3.jar with timestamp 1607186022972
20/12/06 00:33:43 INFO Executor: Starting executor ID driver on host localhost
20/12/06 00:33:43 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 49301.
20/12/06 00:33:43 INFO NettyBlockTransferService: Server created on 172.20.10.2:49301
20/12/06 00:33:43 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
20/12/06 00:33:43 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, 172.20.10.2, 49301, None)
20/12/06 00:33:43 INFO BlockManagerMasterEndpoint: Registering block manager 172.20.10.2:49301 with 2004.6 MB RAM, BlockManagerId(driver, 172.20.10.2, 49301, None)
20/12/06 00:33:43 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, 172.20.10.2, 49301, None)
20/12/06 00:33:43 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, 172.20.10.2, 49301, None)
20/12/06 00:33:46 INFO SharedState: Setting hive.metastore.warehouse.dir ('null') to the value of spark.sql.warehouse.dir ('file:/Users/shuzeyuan/IdeaProjects/SparrowRecSys/spark-warehouse').
20/12/06 00:33:46 INFO SharedState: Warehouse path is 'file:/Users/shuzeyuan/IdeaProjects/SparrowRecSys/spark-warehouse'.
20/12/06 00:33:46 INFO StateStoreCoordinatorRef: Registered StateStoreCoordinator endpoint
Exception in thread "main" java.util.ServiceConfigurationError: org.apache.spark.sql.sources.DataSourceRegister: Provider com.linkedin.spark.datasources.tfrecord.DefaultSource could not be instantiated
	at java.util.ServiceLoader.fail(ServiceLoader.java:232)
	at java.util.ServiceLoader.access$100(ServiceLoader.java:185)
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:384)
	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
	at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
	at scala.collection.convert.Wrappers$JIteratorWrapper.next(Wrappers.scala:43)
	at scala.collection.Iterator$class.foreach(Iterator.scala:891)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1334)
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at scala.collection.TraversableLike$class.filterImpl(TraversableLike.scala:247)
	at scala.collection.TraversableLike$class.filter(TraversableLike.scala:259)
	at scala.collection.AbstractTraversable.filter(Traversable.scala:104)
	at org.apache.spark.sql.execution.datasources.DataSource$.lookupDataSource(DataSource.scala:630)
	at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:245)
	at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:229)
	at com.wzhe.sparrowrecsys.offline.spark.featureeng.waterman.TestTFExample$.main(TestTFExample.scala:42)
	at com.wzhe.sparrowrecsys.offline.spark.featureeng.waterman.TestTFExample.main(TestTFExample.scala)
Caused by: java.lang.NoSuchMethodError: org.apache.spark.sql.execution.datasources.FileFormat.$init$(Lorg/apache/spark/sql/execution/datasources/FileFormat;)V
	at com.linkedin.spark.datasources.tfrecord.DefaultSource.<init>(DefaultSource.scala:23)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:380)
	... 15 more
20/12/06 00:33:47 INFO SparkContext: Invoking stop() from shutdown hook
20/12/06 00:33:47 INFO SparkUI: Stopped Spark web UI at http://172.20.10.2:4040
20/12/06 00:33:47 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
20/12/06 00:33:47 INFO MemoryStore: MemoryStore cleared
20/12/06 00:33:47 INFO BlockManager: BlockManager stopped
20/12/06 00:33:47 INFO BlockManagerMaster: BlockManagerMaster stopped
20/12/06 00:33:47 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
20/12/06 00:33:47 INFO SparkContext: Successfully stopped SparkContext
20/12/06 00:33:47 INFO ShutdownHookManager: Shutdown hook called
20/12/06 00:33:47 INFO ShutdownHookManager: Deleting directory /private/var/folders/9z/ct0p8j1d74z5yp89434ncgbc0000gn/T/spark-3547b835-b000-4f49-a890-11c7660c4388

**Comment by junshi15** [comment]
You were running Spark version 2.4.3. Was it built for scala 2.11 or 2.12?

If it is scala 2.11, please try spark-tfrecord_2.11 v0.2.4
https://mvnrepository.com/artifact/com.linkedin.sparktfrecord/spark-tfrecord_2.11/0.2.4

If it is scala 2.12, please try spark-tfrecord_2.12 v0.2.4
https://mvnrepository.com/artifact/com.linkedin.sparktfrecord/spark-tfrecord_2.12/0.2.4

**Comment by Mowar** [comment]
@junshi15 Thank you. My problem has been solved,

**Comment by junshi15** [comment]
great! closing the issue.
