### ISSUE TITLE
Overwrite mode with partitionby option overwrite the entire data instead of the partition of the data

### ISSUE THREAD

**Issue by sketchmind** [linkedin/spark-tfrecord#18]
spark3.0.1,hadoop3.2 on yarn.
source parquet,deltalake work normally but tfrecord does not match expectations.

**Comment by junshi15** [comment]
Thanks for trying out spark-tfrecord.
Can you provide a code snippet showing two different behaviors, parquet vs tfrecord?

**Comment by zetaatlyft** [comment]
@sheldon1iu from my experience adding the following spark configuration.
```
'spark.sql.sources.partitionOverwriteMode': 'dynamic',
```
does the trick.

**Comment by sketchmind** [comment]
@junshi15 


**mycode:**
```python
# -*- coding:utf-8 -*-

from pyspark.sql import SparkSession, functions as F

# sparkConf defined on sever,the conf of two examples is same
spark = SparkSession \
    .builder \
    .appName("spark-tfrecord-test") \
    .enableHiveSupport() \
    .getOrCreate()

# make sample data
df = spark.range(3)

for dt in ['2020-12-08', '2020-12-09']:
    sample = df.withColumn("dt", F.lit(dt))
    print(f"show dataframe on date {dt}:")
    sample.show()

    # save sample dataframe use source tfrecord
    sample.repartition(1) \
        .write \
        .partitionBy("dt") \
        .format("tfrecord") \
        .option("recordType", "SequenceExample") \
        .mode("overwrite") \
        .save("hdfs:///data/tfrecord/spark_tfrecord_test")

    # save sample dataframe use source tfrecord
    sample.repartition(1) \
        .write \
        .partitionBy("dt") \
        .format("delta") \
        .mode("overwrite") \
        .save("hdfs:///data/delta/spark_tfrecord_test")
```
**result:**
![image](https://user-images.githubusercontent.com/39169452/101615382-05d80980-3a49-11eb-9a61-b752f9cf149a.png)

![image](https://user-images.githubusercontent.com/39169452/101615223-d9bc8880-3a48-11eb-84b1-4422d0f32eef.png)

**Comment by sketchmind** [comment]
@zetaatlyft  You are right,After setting according to your method, it works normally.thanks a lot!

**Comment by junshi15** [comment]
Thanks @zetaatlyft , I learned a new trick.
@sheldon1iu, I am closing this issue since it is resolved.
