### ISSUE TITLE
I not understand how to run it , use java -cp jar

### ISSUE THREAD

**Issue by TIXhjq** [linkedin/spark-tfrecord#23]
I used maven to type my project into a jar package, but he seems to show that there is no such package. How should this be solved?

1.When I run idea, everything is OK
2.I try to java -cp ....jar com. ...<like this method run> 
get error =>
<img width="1276" alt="截屏2021-04-20 下午12 28 48" src="https://user-images.githubusercontent.com/34066628/115337712-11e08e80-a1d4-11eb-9ef6-221be449cff8.png">

It seems that I didn't type it into the jar package, but I don't know how to solve this problem,
I only use this in my pom.xml
<img width="852" alt="截屏2021-04-20 下午12 36 46" src="https://user-images.githubusercontent.com/34066628/115338317-2e30fb00-a1d5-11eb-900b-2cfc0f3d7f0d.png">

**Comment by junshi15** [comment]
This package needs Spark. Are you saying you launch Spark with "java -cp ..."?
I use spark-submit or spark-shell instead (see the example in README), have not tried with "java -cp ..." on this.

**Comment by TIXhjq** [comment]
Thank you for your reply. I found that the whole jar package of MVN package doesn't seem to have this package. There is something wrong with me.

**Comment by junshi15** [comment]
glad you identified the issue.
