### ISSUE TITLE
how to save Rdd to TFRecord in a distribution environment?

### ISSUE THREAD

**Issue by ICDI0906** [linkedin/spark-tfrecord#24]
how to save Rdd to TFRecord in a distribution environment?

**Comment by junshi15** [comment]
RDD's need to be converted to DataFrames before being  saved to TFRecord.
Please take a look at this example: https://github.com/linkedin/spark-tfrecord#scala-api

**Comment by ICDI0906** [comment]
Is it can only run on a single machine?

**Comment by junshi15** [comment]
yes, it can, just like a regular Spark job where you save Dataframe to different formats. If in the past your save a dataframe to avro or parquet, now you can use a similar API to save to tfrecord. The only change is the output format.
