### ISSUE TITLE
Writing TFRecords breaks in Spark 3.2.0

### ISSUE THREAD

**Issue by M-Anwar** [linkedin/spark-tfrecord#36]
When using the library (com.linkedin.sparktfrecord:spark-tfrecord_2.12:0.3.0) in Spark 3.2.0 to write tfrecords the job throws an exception:

`Caused by: java.lang.AbstractMethodError: Receiver class com.linkedin.spark.datasources.tfrecord.TFRecordOutputWriter does not define or inherit an implementation of the resolved method 'abstract java.lang.String path()' of abstract class org.apache.spark.sql.execution.datasources.OutputWriter.`

I think this is caused by the change [SPARK-26164](https://issues.apache.org/jira/browse/SPARK-26164), which modifies the `OutputWriter` class to include a `path(): String` method ([source](https://github.com/apache/spark/blob/master/sql/core/src/main/scala/org/apache/spark/sql/execution/datasources/OutputWriter.scala#L74)).

The current `TFRecordOutputWriter` class doesn't have this method, and hence the error ([source](https://github.com/linkedin/spark-tfrecord/blob/master/src/main/scala/com/linkedin/spark/datasources/tfrecord/TFRecordOutputWriter.scala#L12))

**Comment by junshi15** [comment]
Thanks for reporting the issue.
It looks like this is a breaking change on Spark side.
Do you have a solution already? Your contribution is highly appreciated as we don't have much bandwidth on this project at this moment.

**Comment by tangyl** [comment]
fix: https://github.com/linkedin/spark-tfrecord/pull/37

**Comment by junshi15** [comment]
@M-Anwar can you verify https://github.com/linkedin/spark-tfrecord/pull/37 fixes the issue you raised?
I plan to merge @tangyl 's PR.

**Comment by M-Anwar** [comment]
The solution looks good to me, verified that it works on Spark 3.2.0.  Thanks @tangyl for the PR!

**Comment by junshi15** [comment]
published: https://repo1.maven.org/maven2/com/linkedin/sparktfrecord/spark-tfrecord_2.12/0.3.4/
