### ISSUE TITLE
Publishing to Maven Central

### ISSUE THREAD

**Issue by jamesprinc3** [linkedin/spark-tfrecord#5]
Hello,

Are there any plans to publish the artifacts from this repository to Maven Central? At the moment this repository requires special handling on our end - everything else we just grab straight from Maven.

Thanks,
James

**Comment by junshi15** [comment]
Currently we publish it to Bintray.
https://bintray.com/linkedin/maven/spark-tfrecord
Although it was manually pushed. I will set up the auto-publish sometime next Month, and also push it to Maven Central.

**Comment by junshi15** [comment]
We have published to 
Bintray: https://bintray.com/linkedin/maven/spark-tfrecord
MavenCentral: https://search.maven.org/search?q=spark-tfrecord
