### ISSUE TITLE
How to convert  spark.ml.linalg.VectorUDT datatype to tfrecord?

### ISSUE THREAD

**Issue by mullerhai** [linkedin/spark-tfrecord#55]
HI : 
      I got the data after feature engineer with spark ,the dataframe  column type is  spark.ml.linalg.VectorUDT ,when I want to convert it to tfrecord  meet error.

**Comment by junshi15** [comment]
I don't think VectorUDT is supported. You will need to convert it to ArrayType(FloatType), assuming it's a vector of floats.

**Comment by mullerhai** [comment]
> I don't think VectorUDT is supported. You will need to convert it to ArrayType(FloatType), assuming it's a vector of floats.

yeah, convert to ArrayType  it is ok !
