### ISSUE TITLE
Support for reading ByteArray's from TFRecord files

### ISSUE THREAD

**Issue by asketagarwal** [linkedin/spark-tfrecord#66]
This is a followup to this PR #60 . It introduced a way to write ByteArrays to TFRecord files. We also have a use case where we want to read the ByteArrays from the files that we wrote. I was hoping that I could contribute to the repository by adding support for reading ByteArray's from TfRecord files. 

I have a PR #65 ready for review.

**Comment by junshi15** [comment]
PR merged.
